Baseline protobuf
drumnkyle/music-notation-kit pull request #1
Opened 2017-03-01 02:29 UTC by migue48

2017-03-09 04:44 UTC, drumnkyle requested changes

2017-03-09 04:44 UTC, drumnkyle commented on Sources/MusicNotationKit/FileIO/Protobuf/_StaffLocation+Transform.swift
> +        default:    return StaffLocation.LocationType.space
Remove extra space before `return`. Also, with Swift we always prefer to list all cases explicitly instead of using default.

2017-03-09 04:44 UTC, drumnkyle commented on Sources/MusicNotationKit/FileIO/Protobuf/_Interval+Transform.swift
> +        default: return MusicNotationCore.IntervalQuality.major
Since you declare the return type, you should be able to just put the short version, like `.augmented'.

2017-03-09 04:44 UTC, drumnkyle commented on Proto/_Types.proto
> +    OCT9 = 10;
Any reason you abbreviated instead of spelling it out completely like we do in Swift.

2017-03-11 03:25 UTC, migue48 commented on Proto/_Types.proto
> +    OCT9 = 10;
The protobuf compiler was removing the preffix. Not sure if it is because it matched the type name of the enum.

2017-03-11 03:28 UTC, migue48 commented on Sources/MusicNotationKit/FileIO/Protobuf/_Interval+Transform.swift
> +        default: return MusicNotationCore.IntervalQuality.major
Done.

2020-05-16 22:01 UTC, drumnkyle commented
This is probably not needed anymore and we can just use Codable.

2020-05-19 17:31 UTC, closed without merging